name: proselint
on: [push]

jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - name: try
        run: |
          apt install -y python3-proselint
          find . -name '*.md' -exec proselint {} +
          echo help
        
  
  
