name: shellcheck

on: [push]

jobs: 
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: ludeeus/action-shellcheck@0.1.0
  
  proselint:
    runs-on: ubuntu-latest
    steps:
      - uses: NolanJMcCafferty/proselint-action@v1
