name: proselint
on: [push]

jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: try
        working-directory: docs
        run: |
          ls -la
          echo help
        
  
  
