name: proselint
on: [push]

jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: try
        run: |
          ls
          find . -name '*.md' -exec proselint {} +
  
  
