name: proselint
on: [push]

jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: shellcheck 
        uses: ludeeus/actions/shellcheck@master
    
      - name: proselint
        uses: NolanJMcCafferty/proselint-action@v15
        
  
  
