name: proselint
on: [push]

jobs: 

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
    
      - uses: NolanJMcCafferty/proselint-action@v14
        
  
  
